-- Star Institute Supabase schema
-- Run this file in the Supabase SQL Editor. This is PostgreSQL syntax.

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  level text not null default '',
  description text not null default '',
  overview text not null default '',
  modules text not null default '',
  requirements text not null default '',
  careers text not null default '',
  duration text not null default '',
  study_mode text not null default '',
  intake text not null default '',
  fees_note text not null default '',
  examining_body text not null default '',
  image text not null default '',
  featured boolean not null default false,
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null default 'General',
  excerpt text not null default '',
  body text not null default '',
  image text not null default '',
  published_at timestamptz not null default now(),
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text not null default '',
  body text not null default '',
  image text not null default '',
  event_date timestamptz,
  end_date timestamptz,
  location text not null default '',
  registration_info text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  category text not null default 'General',
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null default '',
  qualifications text not null default '',
  subjects text not null default '',
  experience text not null default '',
  photo text not null default '',
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  image text not null,
  category text not null default 'Campus',
  caption text not null default '',
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  file_url text not null,
  category text not null default 'Other',
  description text not null default '',
  file_size text not null default '',
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  link text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  quote text not null,
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  id_number text not null default '',
  dob text not null default '',
  gender text not null default '',
  address text not null default '',
  academic_level text not null default '',
  school text not null default '',
  grade text not null default '',
  course_id bigint references public.courses(id) on delete set null,
  course_slug text not null default '',
  course_name text not null default '',
  study_mode text not null default '',
  guardian_name text not null default '',
  guardian_phone text not null default '',
  documents_note text not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  subject text not null default '',
  message text not null,
  status text not null default 'unread',
  created_at timestamptz not null default now()
);

create table if not exists public.graduation_requests (
  id bigint generated by default as identity primary key,
  student_names text not null default '',
  email text not null default '',
  phone text not null,
  admission_number text not null default '',
  national_id text not null default '',
  year_completed text not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_tokens (
  token text primary key,
  username text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_courses_published on public.courses (published, featured, display_order);
create index if not exists idx_news_published on public.news (published, published_at);
create index if not exists idx_events_published on public.events (published, event_date);
create index if not exists idx_applications_created on public.applications (created_at);
create index if not exists idx_messages_created on public.messages (created_at);
create index if not exists idx_graduation_created on public.graduation_requests (created_at);

alter table public.courses enable row level security;
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.faqs enable row level security;
alter table public.staff enable row level security;
alter table public.gallery enable row level security;
alter table public.documents enable row level security;
alter table public.announcements enable row level security;
alter table public.testimonials enable row level security;
alter table public.site_settings enable row level security;

-- The Render API uses the service-role key. These policies also allow the browser
-- to read published content directly if the public key is used there later.
do $$
begin
  create policy "public read published courses" on public.courses for select using (published = true);
  create policy "public read published news" on public.news for select using (published = true);
  create policy "public read published events" on public.events for select using (published = true);
  create policy "public read published faqs" on public.faqs for select using (published = true);
  create policy "public read published staff" on public.staff for select using (published = true);
  create policy "public read published gallery" on public.gallery for select using (published = true);
  create policy "public read published documents" on public.documents for select using (published = true);
  create policy "public read published announcements" on public.announcements for select using (published = true);
  create policy "public read published testimonials" on public.testimonials for select using (published = true);
  create policy "public read site settings" on public.site_settings for select using (true);
exception when duplicate_object then null;
end $$;

-- The API creates public submissions with its server-side key.
grant usage on schema public to anon, authenticated, service_role;
grant select on public.courses, public.news, public.events, public.faqs, public.staff, public.gallery, public.documents, public.announcements, public.testimonials, public.site_settings to anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
