-- Star Institute Supabase starter content

insert into public.admin_users (username, password_hash)
values ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9')
on conflict (username) do nothing;

insert into public.courses (slug, name, category, level, description, overview, duration, study_mode, intake, fees_note, examining_body, image, featured, published, display_order)
values
('certified-public-accountant-cpa','Certified Public Accountant (CPA)','Accounting & Finance','Professional (KASNEB)','The flagship KASNEB professional qualification for accountants.','Professional accountancy training across Foundation, Intermediate and Final levels.','Per KASNEB level','Full-Time, Part-Time, Evening','January / May / September','See the official CPA / ATD fee structure and confirm current fees with accounts.','KASNEB','/images/accounting.jpg',true,true,1),
('accounting-technicians-diploma-atd','Accounting Technicians Diploma (ATD)','Accounting & Finance','Professional (KASNEB)','Practical accounting technician training for entry and progression roles.','A structured route into bookkeeping, accounts and finance support.','Per KASNEB level','Full-Time, Part-Time, Evening','January / May / September','See the official CPA / ATD fee structure and confirm current fees with accounts.','KASNEB','/images/accounting.jpg',true,true,2),
('certified-investment-financial-analysts-cifa','Certified Investment & Financial Analysts (CIFA)','Accounting & Finance','Professional (KASNEB)','Investment analysis and financial markets training for aspiring analysts.','','Per KASNEB level','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','KASNEB','/images/accounting.jpg',false,true,3),
('certificate-accounting-management-skills-cams','Certificate in Accounting & Management Skills (CAMS)','Accounting & Finance','Professional (KASNEB)','Foundational accounting and management skills for workplace readiness.','','One semester','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','KASNEB','/images/accounting.jpg',false,true,4),
('certificate-in-business-management','Certificate in Business Management','Management','Certificate','Build practical skills in business operations, leadership and administration.','','1 year','Full-Time, Part-Time, Evening','January / May / September','See the official Management fee structure and confirm current fees with accounts.','KNEC','/images/training.jpg',true,true,5),
('diploma-in-business-management','Diploma in Business Management','Management','Diploma','Develop practical skills for supervising people, projects and business operations.','','2 years','Full-Time, Part-Time, Evening','January / May / September','See the official Management fee structure and confirm current fees with accounts.','KNEC','/images/training.jpg',false,true,6),
('sales-and-marketing','Sales and Marketing (Certificate & Diploma)','Management','Certificate','Training in sales strategy, customer service and marketing practice.','','1-2 years','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','KNEC','/images/training.jpg',false,true,7),
('human-resource-management','Human Resource Management (Certificate & Diploma)','Management','Certificate','Develop practical people-management and workplace administration skills.','','1-2 years','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','KNEC','/images/training.jpg',false,true,8),
('purchasing-and-supplies','Purchasing and Supplies (KISM & CIPS)','Management','Certificate','Purchasing, procurement and supply-chain training aligned with professional practice.','','1-2 years','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','KISM / CIPS','/images/training.jpg',false,true,9),
('clearing-and-forwarding','Clearing and Forwarding (Certificate & Diploma)','Management','Certificate','Practical training for logistics, customs and freight operations.','','1-2 years','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','Institutional','/images/training.jpg',false,true,10),
('diploma-in-maritime-management','Diploma in Maritime Management','Management','Diploma','Management training for maritime, port and shipping environments.','','2 years','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','Institutional','/images/training.jpg',false,true,11),
('information-technology','Information Technology (Certificate & Diploma)','ICT & Computing','Certificate','Hands-on ICT training covering computing, systems and digital workplace skills.','','1-2 years','Full-Time, Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','KNEC','/images/lab.jpg',true,true,12),
('computer-packages','Computer Packages','ICT & Computing','Short Course','Essential office productivity and digital literacy skills.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Institutional','/images/lab.jpg',false,true,13),
('computer-networking','Computer Networking','ICT & Computing','Certificate','Learn network setup, support and troubleshooting fundamentals.','','One year','Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','Institutional','/images/networking.jpg',false,true,14),
('computer-repair-maintenance','Computer Repair & Maintenance','ICT & Computing','Certificate','Practical computer hardware repair, maintenance and troubleshooting.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Institutional','/images/lab.jpg',false,true,15),
('web-and-software-development','Web and Software Development','ICT & Computing','Certificate','Build modern websites and software development foundations.','','One year','Part-Time, Evening','January / May / September','Contact the accounts office for the current fee.','Institutional','/images/lab.jpg',false,true,16),
('graphic-design','Graphic Design','ICT & Computing','Certificate','Develop practical visual communication and digital design skills.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Institutional','/images/lab.jpg',false,true,17),
('enterprise-resource-planning-erp','Enterprise Resource Planning (ERP)','ICT & Computing','Short Course','Introduction to business systems and enterprise resource planning.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Institutional','/images/lab.jpg',false,true,18),
('architectural-packages-autocad-archicad','Architectural Packages (AutoCAD & ArchiCAD)','ICT & Computing','Certificate','Practical architectural drawing and design software training.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Institutional','/images/lab.jpg',false,true,19),
('accounting-packages','Accounting Packages (QuickBooks, Sage, Pastel)','ICT & Computing','Short Course','Hands-on training in widely used accounting software packages.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Institutional','/images/accounting.jpg',false,true,20),
('ccna-cisco-certified-network-associate','CCNA (Cisco Certified Network Associate)','Cisco Network Academy','Professional (Cisco)','Networking fundamentals, routing, switching and network security.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Cisco Network Academy','/images/networking.jpg',true,true,21),
('it-essentials','IT Essentials','Cisco Network Academy','Professional (Cisco)','Computer hardware, software and troubleshooting foundations.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Cisco Network Academy','/images/networking.jpg',false,true,22),
('networking-essentials','Networking Essentials','Cisco Network Academy','Professional (Cisco)','Core networking concepts and small-network setup for beginners.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Cisco Network Academy','/images/networking.jpg',false,true,23),
('cybersecurity-operations-cyberops','CyberSecurity Operations (CyberOps)','Cisco Network Academy','Professional (Cisco)','Security monitoring, analysis and incident-response foundations.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Cisco Network Academy','/images/networking.jpg',false,true,24),
('cybersecurity-essentials','CyberSecurity Essentials','Cisco Network Academy','Professional (Cisco)','Digital security principles for ICT professionals.','','One semester','Part-Time, Evening','Rolling intakes','Contact the accounts office for the current fee.','Cisco Network Academy','/images/networking.jpg',false,true,25),
('certificate-in-cosmetology','Certificate in Cosmetology','Beauty & Cosmetology','Certificate','Beauty therapy foundations with practical salon training.','','1 year','Full-Time, Part-Time','January / May / September','See the official Beauty & Cosmetology fee structure and confirm current fees with accounts.','KNEC / Institutional','/images/beauty.jpg',false,true,26),
('diploma-in-cosmetology','Diploma in Cosmetology','Beauty & Cosmetology','Diploma','Advanced beauty therapy, treatments and salon management.','','2 years','Full-Time, Part-Time','January / May / September','See the official Beauty & Cosmetology fee structure and confirm current fees with accounts.','KNEC / Institutional','/images/beauty.jpg',false,true,27),
('certificate-in-hairdressing-beauty-therapy','Certificate in Hairdressing & Beauty Therapy','Beauty & Cosmetology','Certificate','Hair care, styling, braiding, colour and beauty therapy practice.','','1 year','Full-Time, Part-Time','January / May / September','See the official Beauty & Cosmetology fee structure and confirm current fees with accounts.','KNEC / Institutional','/images/beauty.jpg',false,true,28),
('certificate-electrical-electronics-engineering','Certificate in Electrical & Electronics Engineering','Engineering','Certificate','Practical wiring, circuits, electronics and workshop safety training.','','1 year','Full-Time, Part-Time','January / May / September','Contact the accounts office for the current engineering fee schedule.','KNEC','/images/engineering.jpg',false,true,29),
('diploma-electrical-electronics-engineering','Diploma in Electrical & Electronics Engineering','Engineering','Diploma','Advanced electrical installations, machines, power systems and control.','','2 years','Full-Time, Part-Time','January / May / September','Contact the accounts office for the current engineering fee schedule.','KNEC','/images/engineering.jpg',false,true,30),
('consultancy-corporate-training','Consultancy & Corporate Training','Consultancy & Training','Service','Tailored consultancy, workshops, seminars and corporate training.','','Tailored','On-site, At Campus','On demand','Request a quotation from the institute.','Institutional','/images/classroom.jpg',false,true,31)
on conflict (slug) do update set name = excluded.name, category = excluded.category, level = excluded.level, description = excluded.description, duration = excluded.duration, study_mode = excluded.study_mode, intake = excluded.intake, fees_note = excluded.fees_note, examining_body = excluded.examining_body, image = excluded.image, featured = excluded.featured, published = excluded.published, display_order = excluded.display_order;

insert into public.documents (title, file_url, category, description, file_size, published, display_order)
values
('CPA & ATD Fee Structure','/downloads/CPA-ATD-FEES-STRUCTURE.pdf','Fee Structure','Official CPA and ATD fee schedule. Confirm current fees with the accounts office before payment.','PDF',true,1),
('Management Programmes Fee Structure','/downloads/MANAGEMENT-FEE-STRUCTURE.pdf','Fee Structure','Official Management programmes fee schedule. Confirm current fees with the accounts office before payment.','PDF',true,2),
('Beauty & Cosmetology Fee Structure','/downloads/BEAUTY-COSMETOLOGY-FEE-STRUCTURE.pdf','Fee Structure','Official Beauty & Cosmetology fee schedule. Confirm current fees with the accounts office before payment.','PDF',true,3),
('Star Institute Brochure 2024','/downloads/STAR-BROCHURE-2024.pdf','Brochure','The official institute brochure — programmes, campus and student life overview.','PDF',true,4)
on conflict do nothing;

insert into public.site_settings (key, value)
values ('admissions_email','starinstitute.msa@gmail.com'), ('admissions_phone','+254 704 978 271')
on conflict (key) do update set value = excluded.value;
